name: WEB
'on':
  push:
    branches:
      - main
      - feature/**

jobs:
  BUILD_AND_DEPLOY_DEV:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: USE NODE.JS 
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: INSTALL NODE DEPENDENCIES
        run: |
          npm i
          npm i -g firebase-tools@11.0.1 
      # - name: RUN TEST
      #   run: |
      #     npx ng test --codeCoverage
      # - name: VALIDATE CONDITIONS OF GOOD SOFTWARE
        # run: |
        #   cd scripts
        #   python3 validate-coverage.py --path ../coverage/lcov-report/index.html

      - name: BUILD DEV
        run: |
          npm run build:dev
      - name: DEPLOY DEV
        run: |
          echo "${{secrets.FIREBASE_WEB_CONFIG}}" > src/environments/environment.ts
          firebase use dev --token "${{secrets.FIREBASE_TOKEN}}"
          firebase deploy --token "${{secrets.FIREBASE_TOKEN}}" 

  # BUILD_AND_DEPLOY_PDN:
  #   needs: [BUILD_AND_DEPLOY_DEV]
  #   runs-on: ubuntu-latest
  #   environment: pdn
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: USE NODE.JS 
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 14.x
  #     - name: INSTALL NODE DEPENDENCIES
  #       run: |
  #         cd web
  #         npm i
  #         npm i -g firebase-tools@11.0.1 
  #     # - name: RUN TEST
  #     #   run: |
  #     #     cd web
  #     #     npx ng test --codeCoverage
  #     # - name: VALIDATE CONDITIONS OF GOOD SOFTWARE
  #       # run: |
  #       #   cd web/scripts
  #       #   python3 validate-coverage.py --path ../coverage/lcov-report/index.html
  #     - name: BUILD ENTITIES
  #       run: |
  #         cd entities
  #         npm run build:pipeline
  #     - name: BUILD PDN
  #       run: |
  #         cd web
  #         cat src/environments/environment.ts
  #         echo "${{secrets.FIREBASE_WEB_CONFIG}}" > src/environments/environment.ts
  #         cat src/environments/environment.ts
  #         npm run build:pdn
  #     - name: DEPLOY PDN
  #       run: |
  #         cd web
  #         echo "${{secrets.FIREBASE_WEB_CONFIG}}" > src/environments/environment.ts
  #         firebase use pdn --token "${{secrets.FIREBASE_TOKEN}}"
  #         firebase deploy --token "${{secrets.FIREBASE_TOKEN}}" 
